wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.2
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705101451.742081
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 22
      - 23
      - 35
      4: 3.8.2
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.MultiInputPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''net_arch'': [512, 512, 512, 512], ''use_sde'': False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 150000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1705101463761014900
learning_rate:
  desc: null
  value: 0.001
tensorboard_log:
  desc: null
  value: runs
_last_obs:
  desc: null
  value: "OrderedDict([('achieved_goal', array([[ 2.5228605e+00,  5.6607475e+00, -1.0450474e+00,\
    \ -8.3202010e-01,\n         4.4477420e+00,  5.3667510e-01,  0.0000000e+00,  0.0000000e+00,\n\
    \        -1.0450474e+00, -8.3202010e-01,  0.0000000e+00,  0.0000000e+00,\n   \
    \      5.1729760e+00,  3.4622808e+00,  3.4472513e+00,  6.2428565e+00,\n      \
    \   6.3311839e+00,  6.4478588e+00,  6.5954328e+00,  6.2620134e+00,\n         5.0000000e+03,\
    \  4.9791832e+00,  5.0000000e+03,  5.0000000e+03,\n         5.0000000e+03,  5.0000000e+03,\
    \  5.0000000e+03,  5.0000000e+03,\n         5.0000000e+03,  3.0445733e+00,  5.0000000e+03,\
    \  5.0000000e+03,\n         5.0000000e+03,  5.0000000e+03,  2.7160892e+00,  5.0000000e+03,\n\
    \         2.6732550e+00,  5.0000000e+03,  5.0000000e+03,  2.6891849e+00,\n   \
    \      2.7160892e+00,  2.7545180e+00,  2.8052800e+00,  2.8694851e+00,\n      \
    \   2.9486074e+00,  3.0445733e+00,  3.1598859e+00,  3.2978046e+00,\n         3.4626009e+00,\
    \  3.6599379e+00,  3.8974380e+00,  4.1855655e+00,\n         4.5390387e+00,  4.9791832e+00,\
    \  5.5380583e+00,  6.2661099e+00,\n         7.2474923e+00,  8.6337643e+00,  8.5250883e+00,\
    \  8.4061537e+00,\n         8.3228855e+00,  5.5472736e+00,  7.2543507e+00,  7.2686934e+00,\n\
    \         7.3120079e+00,  5.3555598e+00,  4.2572861e+00,  4.3357415e+00,\n   \
    \      4.4349751e+00,  4.5572639e+00,  4.7055850e+00,  4.8838081e+00,\n      \
    \   5.0969701e+00,  6.7936907e+00,  6.3261452e+00,  5.9407458e+00,\n         5.6205158e+00,\
    \  5.3530889e+00,  5.1292782e+00,  4.9421535e+00,\n         4.7864261e+00,  4.6580343e+00,\
    \  4.5538535e+00,  4.4714913e+00,\n         4.4091473e+00,  4.3655100e+00,  4.3396864e+00,\
    \  4.3311596e+00,\n         4.3397593e+00,  4.3656569e+00,  4.4093719e+00,  4.4717975e+00,\n\
    \         4.5542479e+00,  4.6585264e+00,  4.7870269e+00,  4.9428782e+00,\n   \
    \      3.8275104e+00,  3.4891701e+00,  3.2174544e+00,  2.9959700e+00,\n      \
    \   2.8134031e+00,  2.6617098e+00,  2.5350304e+00,  2.4290121e+00,\n         2.3403709e+00,\
    \  2.3159654e+00,  2.6786861e+00,  3.1910546e+00,\n         5.3407660e+00,  5.2662559e+00,\
    \  5.2140903e+00,  5.1832037e+00]],\n      dtype=float32)), ('desired_goal', array([[0.,\
    \ 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,\n        0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0.]],\n      dtype=float32)), ('observation',\
    \ array([[ 2.5228605e+00,  5.6607475e+00, -1.0450474e+00, -8.3202010e-01,\n  \
    \       4.4477420e+00,  5.3667510e-01,  0.0000000e+00,  0.0000000e+00,\n     \
    \   -1.0450474e+00, -8.3202010e-01,  0.0000000e+00,  0.0000000e+00,\n        \
    \ 5.1729760e+00,  3.4622808e+00,  3.4472513e+00,  6.2428565e+00,\n         6.3311839e+00,\
    \  6.4478588e+00,  6.5954328e+00,  6.2620134e+00,\n         5.0000000e+03,  4.9791832e+00,\
    \  5.0000000e+03,  5.0000000e+03,\n         5.0000000e+03,  5.0000000e+03,  5.0000000e+03,\
    \  5.0000000e+03,\n         5.0000000e+03,  3.0445733e+00,  5.0000000e+03,  5.0000000e+03,\n\
    \         5.0000000e+03,  5.0000000e+03,  2.7160892e+00,  5.0000000e+03,\n   \
    \      2.6732550e+00,  5.0000000e+03,  5.0000000e+03,  2.6891849e+00,\n      \
    \   2.7160892e+00,  2.7545180e+00,  2.8052800e+00,  2.8694851e+00,\n         2.9486074e+00,\
    \  3.0445733e+00,  3.1598859e+00,  3.2978046e+00,\n         3.4626009e+00,  3.6599379e+00,\
    \  3.8974380e+00,  4.1855655e+00,\n         4.5390387e+00,  4.9791832e+00,  5.5380583e+00,\
    \  6.2661099e+00,\n         7.2474923e+00,  8.6337643e+00,  8.5250883e+00,  8.4061537e+00,\n\
    \         8.3228855e+00,  5.5472736e+00,  7.2543507e+00,  7.2686934e+00,\n   \
    \      7.3120079e+00,  5.3555598e+00,  4.2572861e+00,  4.3357415e+00,\n      \
    \   4.4349751e+00,  4.5572639e+00,  4.7055850e+00,  4.8838081e+00,\n         5.0969701e+00,\
    \  6.7936907e+00,  6.3261452e+00,  5.9407458e+00,\n         5.6205158e+00,  5.3530889e+00,\
    \  5.1292782e+00,  4.9421535e+00,\n         4.7864261e+00,  4.6580343e+00,  4.5538535e+00,\
    \  4.4714913e+00,\n         4.4091473e+00,  4.3655100e+00,  4.3396864e+00,  4.3311596e+00,\n\
    \         4.3397593e+00,  4.3656569e+00,  4.4093719e+00,  4.4717975e+00,\n   \
    \      4.5542479e+00,  4.6585264e+00,  4.7870269e+00,  4.9428782e+00,\n      \
    \   3.8275104e+00,  3.4891701e+00,  3.2174544e+00,  2.9959700e+00,\n         2.8134031e+00,\
    \  2.6617098e+00,  2.5350304e+00,  2.4290121e+00,\n         2.3403709e+00,  2.3159654e+00,\
    \  2.6786861e+00,  3.1910546e+00,\n         5.3407660e+00,  5.2662559e+00,  5.2140903e+00,\
    \  5.1832037e+00]],\n      dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001C257F23AC0>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''achieved_goal'': Box(-1.0, 1.0, (112,), float32), ''desired_goal'':
    Box(-1.0, 1.0, (112,), float32), ''observation'': Box(-1.0, 1.0, (112,), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (2,), float32)
n_envs:
  desc: null
  value: 1
buffer_size:
  desc: null
  value: 1000000
batch_size:
  desc: null
  value: 1024
learning_starts:
  desc: null
  value: 100
tau:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.her.her_replay_buffer.HerReplayBuffer object at 0x000001C257F23400>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.her.her_replay_buffer.HerReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{''n_sampled_goal'': 4, ''goal_selection_strategy'': ''future'', ''env'':
    <frcenv.FRCEnv object at 0x000001C2469DFCD0>}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -2.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x000001C257F9AF70>
policy:
  desc: null
  value: "MultiInputPolicy(\n  (actor): Actor(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (latent_pi):\
    \ Sequential(\n      (0): Linear(in_features=336, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n    )\n    (mu): Linear(in_features=512, out_features=2, bias=True)\n\
    \    (log_std): Linear(in_features=512, out_features=2, bias=True)\n  )\n  (critic):\
    \ ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n      (extractors):\
    \ ModuleDict(\n        (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n   \
    \     (desired_goal): Flatten(start_dim=1, end_dim=-1)\n        (observation):\
    \ Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0): Sequential(\n \
    \     (0): Linear(in_features=338, out_features=512, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=512, out_features=512, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=512, out_features=512, bias=True)\n      (5): ReLU()\n\
    \      (6): Linear(in_features=512, out_features=512, bias=True)\n      (7): ReLU()\n\
    \      (8): Linear(in_features=512, out_features=1, bias=True)\n    )\n    (qf1):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n  )\n  (critic_target): ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n    (qf1): Sequential(\n      (0): Linear(in_features=338, out_features=512,\
    \ bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1,\
    \ bias=True)\n    )\n  )\n)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): CombinedExtractor(\n    (extractors): ModuleDict(\n\
    \      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n      (desired_goal):\
    \ Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=336,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n  )\n  (mu): Linear(in_features=512,\
    \ out_features=2, bias=True)\n  (log_std): Linear(in_features=512, out_features=2,\
    \ bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x000001C2E547D760>
