wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.2
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705152353.218307
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 3
      - 22
      - 23
      - 35
      4: 3.8.2
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.MultiInputPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''net_arch'': [512, 512, 512, 512], ''use_sde'': False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 150000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1705152357685183900
learning_rate:
  desc: null
  value: 0.001
tensorboard_log:
  desc: null
  value: runs
_last_obs:
  desc: null
  value: "OrderedDict([('achieved_goal', array([[-1.9071524e-01,  5.3373730e-01, -6.5725595e-01,\
    \  4.0507323e-01,\n         4.6921715e-01, -3.3326069e-01,  0.0000000e+00,  0.0000000e+00,\n\
    \        -3.2862797e-01,  2.0253661e-01,  0.0000000e+00,  0.0000000e+00,\n   \
    \      1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  5.2338664e-04,\n      \
    \   5.3079182e-04,  5.4057362e-04,  5.5294583e-04,  5.6819263e-04,\n         5.8668508e-04,\
    \  6.0890563e-04,  6.3548237e-04,  6.6723843e-04,\n         7.0526497e-04,  1.0000000e+00,\
    \  1.0000000e+00,  8.7466644e-04,\n         9.5948175e-04,  1.0671762e-03,  1.0000000e+00,\
    \  1.0578362e-03,\n         1.0000000e+00,  1.0154536e-03,  1.0012868e-03,  1.0000000e+00,\n\
    \         9.8549586e-04,  9.8355126e-04,  1.0000000e+00,  1.0000000e+00,\n   \
    \      1.0012868e-03,  1.0000000e+00,  1.0000000e+00,  1.0578362e-03,\n      \
    \   1.0000000e+00,  1.1223825e-03,  1.0000000e+00,  1.0000000e+00,\n         1.2764884e-03,\
    \  1.0000000e+00,  1.4367913e-03,  1.5430095e-03,\n         1.6733174e-03,  1.8355768e-03,\
    \  2.0416062e-03,  2.3100027e-03,\n         1.0000000e+00,  2.6135775e-03,  2.5662845e-03,\
    \  2.5304817e-03,\n         2.5054158e-03,  2.4905745e-03,  2.4856599e-03,  2.4905745e-03,\n\
    \         2.5054158e-03,  2.2205487e-03,  1.6734258e-03,  1.3468819e-03,\n   \
    \      1.1307043e-03,  9.7764796e-04,  8.6409145e-04,  7.7691657e-04,\n      \
    \   7.0825830e-04,  6.5311801e-04,  6.0817011e-04,  5.7111931e-04,\n         5.4033368e-04,\
    \  5.1462435e-04,  4.9310812e-04,  4.7511869e-04,\n         4.6014768e-04,  4.4780463e-04,\
    \  4.3778910e-04,  4.2987114e-04,\n         4.2387765e-04,  4.1968250e-04,  4.1719995e-04,\
    \  4.1638021e-04,\n         4.1720696e-04,  4.1969665e-04,  4.2389921e-04,  4.2990057e-04,\n\
    \         4.3782702e-04,  4.4785193e-04,  4.6020545e-04,  4.7518837e-04,\n   \
    \      4.9319159e-04,  5.1472412e-04,  5.4045295e-04,  5.7126238e-04,\n      \
    \   6.0834287e-04,  6.5332861e-04,  1.0000000e+00,  1.0000000e+00,\n         5.8668508e-04,\
    \  5.6819263e-04,  5.5294583e-04,  5.4057362e-04,\n         5.3079182e-04,  1.0000000e+00,\
    \  1.0000000e+00,  1.0000000e+00]],\n      dtype=float32)), ('desired_goal', array([[0.,\
    \ 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,\n        0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0.]],\n      dtype=float32)), ('observation',\
    \ array([[-1.9071524e-01,  5.3373730e-01, -6.5725595e-01,  4.0507323e-01,\n  \
    \       4.6921715e-01, -3.3326069e-01,  0.0000000e+00,  0.0000000e+00,\n     \
    \   -3.2862797e-01,  2.0253661e-01,  0.0000000e+00,  0.0000000e+00,\n        \
    \ 1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  5.2338664e-04,\n         5.3079182e-04,\
    \  5.4057362e-04,  5.5294583e-04,  5.6819263e-04,\n         5.8668508e-04,  6.0890563e-04,\
    \  6.3548237e-04,  6.6723843e-04,\n         7.0526497e-04,  1.0000000e+00,  1.0000000e+00,\
    \  8.7466644e-04,\n         9.5948175e-04,  1.0671762e-03,  1.0000000e+00,  1.0578362e-03,\n\
    \         1.0000000e+00,  1.0154536e-03,  1.0012868e-03,  1.0000000e+00,\n   \
    \      9.8549586e-04,  9.8355126e-04,  1.0000000e+00,  1.0000000e+00,\n      \
    \   1.0012868e-03,  1.0000000e+00,  1.0000000e+00,  1.0578362e-03,\n         1.0000000e+00,\
    \  1.1223825e-03,  1.0000000e+00,  1.0000000e+00,\n         1.2764884e-03,  1.0000000e+00,\
    \  1.4367913e-03,  1.5430095e-03,\n         1.6733174e-03,  1.8355768e-03,  2.0416062e-03,\
    \  2.3100027e-03,\n         1.0000000e+00,  2.6135775e-03,  2.5662845e-03,  2.5304817e-03,\n\
    \         2.5054158e-03,  2.4905745e-03,  2.4856599e-03,  2.4905745e-03,\n   \
    \      2.5054158e-03,  2.2205487e-03,  1.6734258e-03,  1.3468819e-03,\n      \
    \   1.1307043e-03,  9.7764796e-04,  8.6409145e-04,  7.7691657e-04,\n         7.0825830e-04,\
    \  6.5311801e-04,  6.0817011e-04,  5.7111931e-04,\n         5.4033368e-04,  5.1462435e-04,\
    \  4.9310812e-04,  4.7511869e-04,\n         4.6014768e-04,  4.4780463e-04,  4.3778910e-04,\
    \  4.2987114e-04,\n         4.2387765e-04,  4.1968250e-04,  4.1719995e-04,  4.1638021e-04,\n\
    \         4.1720696e-04,  4.1969665e-04,  4.2389921e-04,  4.2990057e-04,\n   \
    \      4.3782702e-04,  4.4785193e-04,  4.6020545e-04,  4.7518837e-04,\n      \
    \   4.9319159e-04,  5.1472412e-04,  5.4045295e-04,  5.7126238e-04,\n         6.0834287e-04,\
    \  6.5332861e-04,  1.0000000e+00,  1.0000000e+00,\n         5.8668508e-04,  5.6819263e-04,\
    \  5.5294583e-04,  5.4057362e-04,\n         5.3079182e-04,  1.0000000e+00,  1.0000000e+00,\
    \  1.0000000e+00]],\n      dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x0000015AC78F0F10>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''achieved_goal'': Box(-1.0, 1.0, (112,), float32), ''desired_goal'':
    Box(-1.0, 1.0, (112,), float32), ''observation'': Box(-1.0, 1.0, (112,), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (2,), float32)
n_envs:
  desc: null
  value: 1
buffer_size:
  desc: null
  value: 1000000
batch_size:
  desc: null
  value: 1024
learning_starts:
  desc: null
  value: 100
tau:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.her.her_replay_buffer.HerReplayBuffer object at 0x0000015AC797DFA0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.her.her_replay_buffer.HerReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{''n_sampled_goal'': 4, ''goal_selection_strategy'': ''future'', ''env'':
    <frcenv.FRCEnv object at 0x0000015AB63DFCD0>}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -2.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x0000015AC78C8820>
policy:
  desc: null
  value: "MultiInputPolicy(\n  (actor): Actor(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (latent_pi):\
    \ Sequential(\n      (0): Linear(in_features=336, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n    )\n    (mu): Linear(in_features=512, out_features=2, bias=True)\n\
    \    (log_std): Linear(in_features=512, out_features=2, bias=True)\n  )\n  (critic):\
    \ ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n      (extractors):\
    \ ModuleDict(\n        (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n   \
    \     (desired_goal): Flatten(start_dim=1, end_dim=-1)\n        (observation):\
    \ Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0): Sequential(\n \
    \     (0): Linear(in_features=338, out_features=512, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=512, out_features=512, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=512, out_features=512, bias=True)\n      (5): ReLU()\n\
    \      (6): Linear(in_features=512, out_features=512, bias=True)\n      (7): ReLU()\n\
    \      (8): Linear(in_features=512, out_features=1, bias=True)\n    )\n    (qf1):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n  )\n  (critic_target): ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n    (qf1): Sequential(\n      (0): Linear(in_features=338, out_features=512,\
    \ bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1,\
    \ bias=True)\n    )\n  )\n)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): CombinedExtractor(\n    (extractors): ModuleDict(\n\
    \      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n      (desired_goal):\
    \ Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=336,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n  )\n  (mu): Linear(in_features=512,\
    \ out_features=2, bias=True)\n  (log_std): Linear(in_features=512, out_features=2,\
    \ bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x0000015B54D74D30>
