wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.2
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705096726.229722
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 22
      - 23
      - 35
      4: 3.8.2
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.MultiInputPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''net_arch'': [512, 512, 512, 512], ''use_sde'': False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 150000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1705096739356400100
learning_rate:
  desc: null
  value: 0.001
tensorboard_log:
  desc: null
  value: runs
_last_obs:
  desc: null
  value: "OrderedDict([('achieved_goal', array([[-2.5361390e+00,  7.2466307e+00, -2.8977182e+00,\
    \ -5.5632621e-01,\n         4.3453212e+00, -3.2820705e-01,  0.0000000e+00,  0.0000000e+00,\n\
    \        -2.8977182e+00, -5.5632621e-01,  0.0000000e+00,  0.0000000e+00,\n   \
    \      3.3203051e+00,  3.3268700e+00,  3.3466949e+00,  2.6314917e+00,\n      \
    \   1.9827600e+00,  1.6480600e+00,  1.6857795e+00,  1.7322626e+00,\n         4.8836870e+00,\
    \  4.5920329e+00,  5.0051098e+00,  4.6180782e+00,\n         4.3001771e+00,  4.0381351e+00,\
    \  3.8204064e+00,  3.6385810e+00,\n         3.4864106e+00,  3.3591821e+00,  3.2533000e+00,\
    \  3.1660016e+00,\n         5.0000000e+03,  3.0391545e+00,  2.9967546e+00,  5.0000000e+03,\n\
    \         5.0000000e+03,  5.0000000e+03,  5.0000000e+03,  2.9670701e+00,\n   \
    \      5.0000000e+03,  5.0000000e+03,  3.0951619e+00,  5.0000000e+03,\n      \
    \   5.0000000e+03,  5.0000000e+03,  5.0000000e+03,  5.0000000e+03,\n         3.8204064e+00,\
    \  5.0000000e+03,  4.3001771e+00,  4.6180782e+00,\n         5.0000000e+03,  5.0000000e+03,\
    \  5.0000000e+03,  6.9136143e+00,\n         7.9964070e+00,  9.5259285e+00,  1.0437853e+01,\
    \  1.0292232e+01,\n         1.0190282e+01,  7.4363098e+00,  9.1070213e+00,  9.1250277e+00,\n\
    \         6.0237050e+00,  6.0839701e+00,  6.1700497e+00,  6.2837548e+00,\n   \
    \      6.4275727e+00,  6.6048050e+00,  8.4166021e+00,  7.5674839e+00,\n      \
    \   6.8987241e+00,  6.3616352e+00,  5.9238243e+00,  5.5629344e+00,\n         5.2630701e+00,\
    \  5.0126510e+00,  4.8030739e+00,  4.6278496e+00,\n         4.4820256e+00,  4.3617992e+00,\
    \  4.2642436e+00,  4.1871200e+00,\n         4.1287408e+00,  4.0878782e+00,  4.0636973e+00,\
    \  4.0557127e+00,\n         4.0637655e+00,  1.5814801e+00,  1.0578003e+00,  7.9702485e-01,\n\
    \         7.4695474e-01,  7.6405048e-01,  7.8511822e-01,  8.1067073e-01,\n   \
    \      8.4137475e-01,  8.7809795e-01,  9.2197788e-01,  9.7452229e-01,\n      \
    \   1.0377609e+00,  1.1144798e+00,  1.2085981e+00,  1.3257945e+00,\n         1.4746046e+00,\
    \  1.6684611e+00,  1.9297713e+00,  3.4911754e+00,\n         3.4280021e+00,  3.3801775e+00,\
    \  3.3466949e+00,  3.3268700e+00]],\n      dtype=float32)), ('desired_goal', array([[0.,\
    \ 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,\n        0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0.]],\n      dtype=float32)), ('observation',\
    \ array([[-2.5361390e+00,  7.2466307e+00, -2.8977182e+00, -5.5632621e-01,\n  \
    \       4.3453212e+00, -3.2820705e-01,  0.0000000e+00,  0.0000000e+00,\n     \
    \   -2.8977182e+00, -5.5632621e-01,  0.0000000e+00,  0.0000000e+00,\n        \
    \ 3.3203051e+00,  3.3268700e+00,  3.3466949e+00,  2.6314917e+00,\n         1.9827600e+00,\
    \  1.6480600e+00,  1.6857795e+00,  1.7322626e+00,\n         4.8836870e+00,  4.5920329e+00,\
    \  5.0051098e+00,  4.6180782e+00,\n         4.3001771e+00,  4.0381351e+00,  3.8204064e+00,\
    \  3.6385810e+00,\n         3.4864106e+00,  3.3591821e+00,  3.2533000e+00,  3.1660016e+00,\n\
    \         5.0000000e+03,  3.0391545e+00,  2.9967546e+00,  5.0000000e+03,\n   \
    \      5.0000000e+03,  5.0000000e+03,  5.0000000e+03,  2.9670701e+00,\n      \
    \   5.0000000e+03,  5.0000000e+03,  3.0951619e+00,  5.0000000e+03,\n         5.0000000e+03,\
    \  5.0000000e+03,  5.0000000e+03,  5.0000000e+03,\n         3.8204064e+00,  5.0000000e+03,\
    \  4.3001771e+00,  4.6180782e+00,\n         5.0000000e+03,  5.0000000e+03,  5.0000000e+03,\
    \  6.9136143e+00,\n         7.9964070e+00,  9.5259285e+00,  1.0437853e+01,  1.0292232e+01,\n\
    \         1.0190282e+01,  7.4363098e+00,  9.1070213e+00,  9.1250277e+00,\n   \
    \      6.0237050e+00,  6.0839701e+00,  6.1700497e+00,  6.2837548e+00,\n      \
    \   6.4275727e+00,  6.6048050e+00,  8.4166021e+00,  7.5674839e+00,\n         6.8987241e+00,\
    \  6.3616352e+00,  5.9238243e+00,  5.5629344e+00,\n         5.2630701e+00,  5.0126510e+00,\
    \  4.8030739e+00,  4.6278496e+00,\n         4.4820256e+00,  4.3617992e+00,  4.2642436e+00,\
    \  4.1871200e+00,\n         4.1287408e+00,  4.0878782e+00,  4.0636973e+00,  4.0557127e+00,\n\
    \         4.0637655e+00,  1.5814801e+00,  1.0578003e+00,  7.9702485e-01,\n   \
    \      7.4695474e-01,  7.6405048e-01,  7.8511822e-01,  8.1067073e-01,\n      \
    \   8.4137475e-01,  8.7809795e-01,  9.2197788e-01,  9.7452229e-01,\n         1.0377609e+00,\
    \  1.1144798e+00,  1.2085981e+00,  1.3257945e+00,\n         1.4746046e+00,  1.6684611e+00,\
    \  1.9297713e+00,  3.4911754e+00,\n         3.4280021e+00,  3.3801775e+00,  3.3466949e+00,\
    \  3.3268700e+00]],\n      dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x0000017850E30AF0>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''achieved_goal'': Box(-1.0, 1.0, (112,), float32), ''desired_goal'':
    Box(-1.0, 1.0, (112,), float32), ''observation'': Box(-1.0, 1.0, (112,), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (2,), float32)
n_envs:
  desc: null
  value: 1
buffer_size:
  desc: null
  value: 1000000
batch_size:
  desc: null
  value: 1024
learning_starts:
  desc: null
  value: 100
tau:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.her.her_replay_buffer.HerReplayBuffer object at 0x0000017850CE1EE0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.her.her_replay_buffer.HerReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{''n_sampled_goal'': 4, ''goal_selection_strategy'': ''future'', ''env'':
    <frcenv.FRCEnv object at 0x000001783F85FC70>}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -2.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x0000017850E28F70>
policy:
  desc: null
  value: "MultiInputPolicy(\n  (actor): Actor(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (latent_pi):\
    \ Sequential(\n      (0): Linear(in_features=336, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n    )\n    (mu): Linear(in_features=512, out_features=2, bias=True)\n\
    \    (log_std): Linear(in_features=512, out_features=2, bias=True)\n  )\n  (critic):\
    \ ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n      (extractors):\
    \ ModuleDict(\n        (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n   \
    \     (desired_goal): Flatten(start_dim=1, end_dim=-1)\n        (observation):\
    \ Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0): Sequential(\n \
    \     (0): Linear(in_features=338, out_features=512, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=512, out_features=512, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=512, out_features=512, bias=True)\n      (5): ReLU()\n\
    \      (6): Linear(in_features=512, out_features=512, bias=True)\n      (7): ReLU()\n\
    \      (8): Linear(in_features=512, out_features=1, bias=True)\n    )\n    (qf1):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n  )\n  (critic_target): ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n    (qf1): Sequential(\n      (0): Linear(in_features=338, out_features=512,\
    \ bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1,\
    \ bias=True)\n    )\n  )\n)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): CombinedExtractor(\n    (extractors): ModuleDict(\n\
    \      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n      (desired_goal):\
    \ Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=336,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n  )\n  (mu): Linear(in_features=512,\
    \ out_features=2, bias=True)\n  (log_std): Linear(in_features=512, out_features=2,\
    \ bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x00000178DE1A5910>
