wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705113123.807483
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 49
      - 55
      3:
      - 22
      - 23
      - 35
      4: 3.10.12
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
