wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.2
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705152235.626594
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 22
      - 23
      - 35
      4: 3.8.2
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.MultiInputPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''net_arch'': [512, 512, 512, 512], ''use_sde'': False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 150000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1705152240051249100
learning_rate:
  desc: null
  value: 0.001
tensorboard_log:
  desc: null
  value: runs
_last_obs:
  desc: null
  value: "OrderedDict([('achieved_goal', array([[ 8.4765649e-01,  3.8552293e-01, -3.6602440e-01,\
    \ -2.3202924e-03,\n         4.6365577e-01, -4.0671343e-01,  0.0000000e+00,  0.0000000e+00,\n\
    \        -1.8301220e-01, -1.1601462e-03,  0.0000000e+00,  0.0000000e+00,\n   \
    \      1.0000000e+00,  9.5284358e-04,  1.0000000e+00,  1.0000000e+00,\n      \
    \   1.0000000e+00,  1.0000000e+00,  1.0227871e-03,  1.0000000e+00,\n         1.0851948e-03,\
    \  1.1262962e-03,  1.0000000e+00,  1.0956221e-03,\n         1.0202012e-03,  1.0000000e+00,\
    \  9.0637739e-04,  8.6323998e-04,\n         8.2713808e-04,  7.9695362e-04,  7.7183347e-04,\
    \  1.0000000e+00,\n         1.0000000e+00,  7.2102825e-04,  1.0000000e+00,  1.0000000e+00,\n\
    \         1.0000000e+00,  6.9837581e-04,  1.0000000e+00,  1.0000000e+00,\n   \
    \      7.1096903e-04,  7.2102825e-04,  1.0000000e+00,  7.5112225e-04,\n      \
    \   7.7183347e-04,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,\n         9.0637739e-04,\
    \  9.5803273e-04,  1.0202012e-03,  1.0000000e+00,\n         1.0000000e+00,  1.3033611e-03,\
    \  1.4496533e-03,  1.6402296e-03,\n         1.8971182e-03,  2.1544748e-03,  2.1154482e-03,\
    \  2.0858957e-03,\n         2.0651957e-03,  2.0529248e-03,  2.0488370e-03,  2.0528510e-03,\n\
    \         2.0650467e-03,  2.0856683e-03,  2.1151376e-03,  2.1540748e-03,\n   \
    \      1.9049564e-03,  1.6470944e-03,  1.4557799e-03,  1.3089118e-03,\n      \
    \   1.1932397e-03,  1.1003419e-03,  1.0246158e-03,  9.6219446e-04,\n         9.1032835e-04,\
    \  8.6701452e-04,  8.3076494e-04,  8.0045720e-04,\n         7.7523477e-04,  7.5443980e-04,\
    \  7.3756609e-04,  7.2422629e-04,\n         7.1412878e-04,  7.0706097e-04,  7.0287852e-04,\
    \  7.0149743e-04,\n         7.0289028e-04,  7.0708484e-04,  7.1416510e-04,  7.2427589e-04,\n\
    \         7.3763001e-04,  7.5451948e-04,  7.7533210e-04,  8.0057461e-04,\n   \
    \      8.3090557e-04,  8.6718251e-04,  9.1052923e-04,  9.6243550e-04,\n      \
    \   1.0249069e-03,  1.1006967e-03,  1.0000000e+00,  1.1262962e-03,\n         1.0000000e+00,\
    \  1.0000000e+00,  1.0000000e+00,  9.9990203e-04,\n         1.0000000e+00,  1.0000000e+00,\
    \  9.5852162e-04,  9.5284358e-04]],\n      dtype=float32)), ('desired_goal', array([[0.,\
    \ 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,\n        0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0.]],\n      dtype=float32)), ('observation',\
    \ array([[ 8.4765649e-01,  3.8552293e-01, -3.6602440e-01, -2.3202924e-03,\n  \
    \       4.6365577e-01, -4.0671343e-01,  0.0000000e+00,  0.0000000e+00,\n     \
    \   -1.8301220e-01, -1.1601462e-03,  0.0000000e+00,  0.0000000e+00,\n        \
    \ 1.0000000e+00,  9.5284358e-04,  1.0000000e+00,  1.0000000e+00,\n         1.0000000e+00,\
    \  1.0000000e+00,  1.0227871e-03,  1.0000000e+00,\n         1.0851948e-03,  1.1262962e-03,\
    \  1.0000000e+00,  1.0956221e-03,\n         1.0202012e-03,  1.0000000e+00,  9.0637739e-04,\
    \  8.6323998e-04,\n         8.2713808e-04,  7.9695362e-04,  7.7183347e-04,  1.0000000e+00,\n\
    \         1.0000000e+00,  7.2102825e-04,  1.0000000e+00,  1.0000000e+00,\n   \
    \      1.0000000e+00,  6.9837581e-04,  1.0000000e+00,  1.0000000e+00,\n      \
    \   7.1096903e-04,  7.2102825e-04,  1.0000000e+00,  7.5112225e-04,\n         7.7183347e-04,\
    \  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,\n         9.0637739e-04,  9.5803273e-04,\
    \  1.0202012e-03,  1.0000000e+00,\n         1.0000000e+00,  1.3033611e-03,  1.4496533e-03,\
    \  1.6402296e-03,\n         1.8971182e-03,  2.1544748e-03,  2.1154482e-03,  2.0858957e-03,\n\
    \         2.0651957e-03,  2.0529248e-03,  2.0488370e-03,  2.0528510e-03,\n   \
    \      2.0650467e-03,  2.0856683e-03,  2.1151376e-03,  2.1540748e-03,\n      \
    \   1.9049564e-03,  1.6470944e-03,  1.4557799e-03,  1.3089118e-03,\n         1.1932397e-03,\
    \  1.1003419e-03,  1.0246158e-03,  9.6219446e-04,\n         9.1032835e-04,  8.6701452e-04,\
    \  8.3076494e-04,  8.0045720e-04,\n         7.7523477e-04,  7.5443980e-04,  7.3756609e-04,\
    \  7.2422629e-04,\n         7.1412878e-04,  7.0706097e-04,  7.0287852e-04,  7.0149743e-04,\n\
    \         7.0289028e-04,  7.0708484e-04,  7.1416510e-04,  7.2427589e-04,\n   \
    \      7.3763001e-04,  7.5451948e-04,  7.7533210e-04,  8.0057461e-04,\n      \
    \   8.3090557e-04,  8.6718251e-04,  9.1052923e-04,  9.6243550e-04,\n         1.0249069e-03,\
    \  1.1006967e-03,  1.0000000e+00,  1.1262962e-03,\n         1.0000000e+00,  1.0000000e+00,\
    \  1.0000000e+00,  9.9990203e-04,\n         1.0000000e+00,  1.0000000e+00,  9.5852162e-04,\
    \  9.5284358e-04]],\n      dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000002327A8F1EE0>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''achieved_goal'': Box(-1.0, 1.0, (112,), float32), ''desired_goal'':
    Box(-1.0, 1.0, (112,), float32), ''observation'': Box(-1.0, 1.0, (112,), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (2,), float32)
n_envs:
  desc: null
  value: 1
buffer_size:
  desc: null
  value: 1000000
batch_size:
  desc: null
  value: 1024
learning_starts:
  desc: null
  value: 100
tau:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.her.her_replay_buffer.HerReplayBuffer object at 0x000002327A8F1F70>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.her.her_replay_buffer.HerReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{''n_sampled_goal'': 4, ''goal_selection_strategy'': ''future'', ''env'':
    <frcenv.FRCEnv object at 0x0000023269410D00>}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -2.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x00000232762A9820>
policy:
  desc: null
  value: "MultiInputPolicy(\n  (actor): Actor(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (latent_pi):\
    \ Sequential(\n      (0): Linear(in_features=336, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n    )\n    (mu): Linear(in_features=512, out_features=2, bias=True)\n\
    \    (log_std): Linear(in_features=512, out_features=2, bias=True)\n  )\n  (critic):\
    \ ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n      (extractors):\
    \ ModuleDict(\n        (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n   \
    \     (desired_goal): Flatten(start_dim=1, end_dim=-1)\n        (observation):\
    \ Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0): Sequential(\n \
    \     (0): Linear(in_features=338, out_features=512, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=512, out_features=512, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=512, out_features=512, bias=True)\n      (5): ReLU()\n\
    \      (6): Linear(in_features=512, out_features=512, bias=True)\n      (7): ReLU()\n\
    \      (8): Linear(in_features=512, out_features=1, bias=True)\n    )\n    (qf1):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n  )\n  (critic_target): ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n    (qf1): Sequential(\n      (0): Linear(in_features=338, out_features=512,\
    \ bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1,\
    \ bias=True)\n    )\n  )\n)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): CombinedExtractor(\n    (extractors): ModuleDict(\n\
    \      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n      (desired_goal):\
    \ Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=336,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n  )\n  (mu): Linear(in_features=512,\
    \ out_features=2, bias=True)\n  (log_std): Linear(in_features=512, out_features=2,\
    \ bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x00000232E7282E50>
