wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.2
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705101653.580133
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 22
      - 23
      - 35
      4: 3.8.2
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
algo:
  desc: null
  value: SAC
policy_class:
  desc: null
  value: <class 'stable_baselines3.sac.policies.MultiInputPolicy'>
device:
  desc: null
  value: cuda
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{''net_arch'': [512, 512, 512, 512], ''use_sde'': False}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 150000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1705101657507676200
learning_rate:
  desc: null
  value: 0.001
tensorboard_log:
  desc: null
  value: runs
_last_obs:
  desc: null
  value: "OrderedDict([('achieved_goal', array([[-7.0172614e-01,  4.0123329e+00, \
    \ 9.4699240e-01,  1.0070531e+00,\n        -2.6120727e+00, -8.4547836e-01,  0.0000000e+00,\
    \  0.0000000e+00,\n         9.4699240e-01,  1.0070531e+00,  0.0000000e+00,  0.0000000e+00,\n\
    \         4.0429225e+00,  4.0509162e+00,  4.0750556e+00,  4.1158252e+00,\n   \
    \      7.3974195e+00,  6.6548820e+00,  5.8208704e+00,  8.9788628e+00,\n      \
    \   9.2710896e+00,  5.0000000e+03,  7.6678567e+00,  5.0000000e+03,\n         6.5839925e+00,\
    \  5.0000000e+03,  5.0000000e+03,  5.0000000e+03,\n         5.0000000e+03,  5.1432371e+00,\
    \  4.9811211e+00,  5.0000000e+03,\n         5.0000000e+03,  4.6532431e+00,  4.5883250e+00,\
    \  4.5428748e+00,\n         4.5159645e+00,  4.5070529e+00,  5.0000000e+03,  5.0000000e+03,\n\
    \         5.0000000e+03,  4.6532431e+00,  4.7389960e+00,  5.0000000e+03,\n   \
    \      4.9811211e+00,  5.1432371e+00,  5.0000000e+03,  5.5710239e+00,\n      \
    \   5.0000000e+03,  5.0000000e+03,  6.5839925e+00,  5.0000000e+03,\n         7.6678567e+00,\
    \  4.1977620e+00,  4.2144132e+00,  4.7684541e+00,\n         5.5152774e+00,  2.2411871e+00,\
    \  2.2006326e+00,  2.1699309e+00,\n         2.1484365e+00,  2.1357100e+00,  2.1314955e+00,\
    \  2.1357100e+00,\n         2.1484365e+00,  2.1699309e+00,  2.2006326e+00,  2.2411871e+00,\n\
    \         2.2924817e+00,  2.3556938e+00,  2.4323626e+00,  2.5244877e+00,\n   \
    \      4.2393489e+00,  3.9092143e+00,  3.6401103e+00,  3.4182911e+00,\n      \
    \   3.2339833e+00,  3.0800674e+00,  2.9512548e+00,  2.8435557e+00,\n         2.7539263e+00,\
    \  2.6800280e+00,  2.6200619e+00,  2.5726514e+00,\n         2.5367599e+00,  2.5116320e+00,\
    \  2.4967537e+00,  2.4918270e+00,\n         2.4967537e+00,  2.5116320e+00,  2.5367599e+00,\
    \  2.5726514e+00,\n         2.6200619e+00,  2.6800280e+00,  2.7539263e+00,  2.8435557e+00,\n\
    \         2.9512548e+00,  3.0800674e+00,  3.2339833e+00,  3.4182911e+00,\n   \
    \      3.6401103e+00,  3.9092143e+00,  4.2393489e+00,  4.6504335e+00,\n      \
    \   5.1724086e+00,  5.8523908e+00,  6.7689776e+00,  4.2509804e+00,\n         4.1740584e+00,\
    \  4.1158252e+00,  4.0750556e+00,  4.0509162e+00]],\n      dtype=float32)), ('desired_goal',\
    \ array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,\n  \
    \      0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n     \
    \   0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0.,\
    \ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],\n      dtype=float32)), ('observation',\
    \ array([[-7.0172614e-01,  4.0123329e+00,  9.4699240e-01,  1.0070531e+00,\n  \
    \      -2.6120727e+00, -8.4547836e-01,  0.0000000e+00,  0.0000000e+00,\n     \
    \    9.4699240e-01,  1.0070531e+00,  0.0000000e+00,  0.0000000e+00,\n        \
    \ 4.0429225e+00,  4.0509162e+00,  4.0750556e+00,  4.1158252e+00,\n         7.3974195e+00,\
    \  6.6548820e+00,  5.8208704e+00,  8.9788628e+00,\n         9.2710896e+00,  5.0000000e+03,\
    \  7.6678567e+00,  5.0000000e+03,\n         6.5839925e+00,  5.0000000e+03,  5.0000000e+03,\
    \  5.0000000e+03,\n         5.0000000e+03,  5.1432371e+00,  4.9811211e+00,  5.0000000e+03,\n\
    \         5.0000000e+03,  4.6532431e+00,  4.5883250e+00,  4.5428748e+00,\n   \
    \      4.5159645e+00,  4.5070529e+00,  5.0000000e+03,  5.0000000e+03,\n      \
    \   5.0000000e+03,  4.6532431e+00,  4.7389960e+00,  5.0000000e+03,\n         4.9811211e+00,\
    \  5.1432371e+00,  5.0000000e+03,  5.5710239e+00,\n         5.0000000e+03,  5.0000000e+03,\
    \  6.5839925e+00,  5.0000000e+03,\n         7.6678567e+00,  4.1977620e+00,  4.2144132e+00,\
    \  4.7684541e+00,\n         5.5152774e+00,  2.2411871e+00,  2.2006326e+00,  2.1699309e+00,\n\
    \         2.1484365e+00,  2.1357100e+00,  2.1314955e+00,  2.1357100e+00,\n   \
    \      2.1484365e+00,  2.1699309e+00,  2.2006326e+00,  2.2411871e+00,\n      \
    \   2.2924817e+00,  2.3556938e+00,  2.4323626e+00,  2.5244877e+00,\n         4.2393489e+00,\
    \  3.9092143e+00,  3.6401103e+00,  3.4182911e+00,\n         3.2339833e+00,  3.0800674e+00,\
    \  2.9512548e+00,  2.8435557e+00,\n         2.7539263e+00,  2.6800280e+00,  2.6200619e+00,\
    \  2.5726514e+00,\n         2.5367599e+00,  2.5116320e+00,  2.4967537e+00,  2.4918270e+00,\n\
    \         2.4967537e+00,  2.5116320e+00,  2.5367599e+00,  2.5726514e+00,\n   \
    \      2.6200619e+00,  2.6800280e+00,  2.7539263e+00,  2.8435557e+00,\n      \
    \   2.9512548e+00,  3.0800674e+00,  3.2339833e+00,  3.4182911e+00,\n         3.6401103e+00,\
    \  3.9092143e+00,  4.2393489e+00,  4.6504335e+00,\n         5.1724086e+00,  5.8523908e+00,\
    \  6.7689776e+00,  4.2509804e+00,\n         4.1740584e+00,  4.1158252e+00,  4.0750556e+00,\
    \  4.0509162e+00]],\n      dtype=float32))])"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x0000028EB8EBF460>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''achieved_goal'': Box(-1.0, 1.0, (112,), float32), ''desired_goal'':
    Box(-1.0, 1.0, (112,), float32), ''observation'': Box(-1.0, 1.0, (112,), float32))'
action_space:
  desc: null
  value: Box(-1.0, 1.0, (2,), float32)
n_envs:
  desc: null
  value: 1
buffer_size:
  desc: null
  value: 1000000
batch_size:
  desc: null
  value: 1024
learning_starts:
  desc: null
  value: 100
tau:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
optimize_memory_usage:
  desc: null
  value: 'False'
replay_buffer:
  desc: null
  value: <stable_baselines3.her.her_replay_buffer.HerReplayBuffer object at 0x0000028EB8EBF9D0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.her.her_replay_buffer.HerReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{''n_sampled_goal'': 4, ''goal_selection_strategy'': ''future'', ''env'':
    <frcenv.FRCEnv object at 0x0000028EA7920D00>}'
_episode_storage:
  desc: null
  value: None
train_freq:
  desc: null
  value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde_at_warmup:
  desc: null
  value: 'False'
target_entropy:
  desc: null
  value: -2.0
log_ent_coef:
  desc: null
  value: tensor([0.], device='cuda:0', requires_grad=True)
ent_coef:
  desc: null
  value: auto
target_update_interval:
  desc: null
  value: 1
ent_coef_optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x0000028EB8E10700>
policy:
  desc: null
  value: "MultiInputPolicy(\n  (actor): Actor(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (latent_pi):\
    \ Sequential(\n      (0): Linear(in_features=336, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n    )\n    (mu): Linear(in_features=512, out_features=2, bias=True)\n\
    \    (log_std): Linear(in_features=512, out_features=2, bias=True)\n  )\n  (critic):\
    \ ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n      (extractors):\
    \ ModuleDict(\n        (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n   \
    \     (desired_goal): Flatten(start_dim=1, end_dim=-1)\n        (observation):\
    \ Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0): Sequential(\n \
    \     (0): Linear(in_features=338, out_features=512, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=512, out_features=512, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=512, out_features=512, bias=True)\n      (5): ReLU()\n\
    \      (6): Linear(in_features=512, out_features=512, bias=True)\n      (7): ReLU()\n\
    \      (8): Linear(in_features=512, out_features=1, bias=True)\n    )\n    (qf1):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n  )\n  (critic_target): ContinuousCritic(\n    (features_extractor): CombinedExtractor(\n\
    \      (extractors): ModuleDict(\n        (achieved_goal): Flatten(start_dim=1,\
    \ end_dim=-1)\n        (desired_goal): Flatten(start_dim=1, end_dim=-1)\n    \
    \    (observation): Flatten(start_dim=1, end_dim=-1)\n      )\n    )\n    (qf0):\
    \ Sequential(\n      (0): Linear(in_features=338, out_features=512, bias=True)\n\
    \      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512, bias=True)\n\
    \      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1, bias=True)\n\
    \    )\n    (qf1): Sequential(\n      (0): Linear(in_features=338, out_features=512,\
    \ bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (5): ReLU()\n      (6): Linear(in_features=512, out_features=512,\
    \ bias=True)\n      (7): ReLU()\n      (8): Linear(in_features=512, out_features=1,\
    \ bias=True)\n    )\n  )\n)"
actor:
  desc: null
  value: "Actor(\n  (features_extractor): CombinedExtractor(\n    (extractors): ModuleDict(\n\
    \      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n      (desired_goal):\
    \ Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=336,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n  )\n  (mu): Linear(in_features=512,\
    \ out_features=2, bias=True)\n  (log_std): Linear(in_features=512, out_features=2,\
    \ bias=True)\n)"
critic:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
critic_target:
  desc: null
  value: "ContinuousCritic(\n  (features_extractor): CombinedExtractor(\n    (extractors):\
    \ ModuleDict(\n      (achieved_goal): Flatten(start_dim=1, end_dim=-1)\n     \
    \ (desired_goal): Flatten(start_dim=1, end_dim=-1)\n      (observation): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=338,\
    \ out_features=512, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (5): ReLU()\n    (6): Linear(in_features=512,\
    \ out_features=512, bias=True)\n    (7): ReLU()\n    (8): Linear(in_features=512,\
    \ out_features=1, bias=True)\n  )\n)"
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x0000028F60E45730>
